### ISSUE TITLE
Ошибка обработки текста

### ISSUE THREAD

**Issue by 4n0n4** [vantu5z/RHVoice-dictionary#224]
Если в тексте попадается подобное

`80-летней`

то выдаёт ошибку
```
Traceback (most recent call last):
  File "###/tools/test_templates.py", line 92, in <module>
    text = text_prepare(txt)
  File "###/tools/preprocessing/text_prepare.py", line 57, in text_prepare
    text = rule.run(text)
  File "###/tools/preprocessing/rules.py", line 39, in run
    new = self.check(m)
  File "###/tools/preprocessing/rules.py", line 670, in check
    num = sub('ста', 'сто', num)
NameError: name 'sub' is not defined
```

**Comment by capricorn2001** [comment]
Спасибо. Буду исправлять.

**Comment by capricorn2001** [comment]
Исправлено.
